background: http://chell.codewithportals.com.s3.amazonaws.com/backgrounds/the-view-from-london.jpg
face: http://chell.codewithportals.com.s3.amazonaws.com/faces/james.jpg
permalink: /:year/:month/:title
title: CodeWithPortals
description: The ramblings of a web developer, living in his natural habitat.
url: http://codewithportals.com

source: .
destination: ./_site
safe: true
lsi: false
pygments: true